services:
  api:
    build: .
    ports:
     - "3333:3333"
    links:
      - database
    depends_on:
      - migration

  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
       - ./create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    environment:
      POSTGRES_PASSWORD: "postgres"
    
  migration:
    build: .
    command: yarn sequelize db:migrate
    links:
      - database
    depends_on:
      - database
      