name: Unity tests

on:
  push:
    branches:
      - develop

  jobs:
    build:
      run-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install modules
          run: yarn
        - name: Running tests
          run: yarn test